#!/usr/bin/env python3
import os
import requests

url = 'http://169.254.169.254/metadata/instance/compute?api-version=2021-02-01'
headers = {'Metadata': 'true'}
instance_metadata = requests.get(url,headers=headers).json()
print(instance_metadata)
data_key = input('Enter the data key to be retrieved :')
metadata_string = instance_metadata[data_key]
metadata_list = metadata_string.split(';')
print (data_key,':',metadata_list)
